# Generated by Django 5.1.15 on 2026-09-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Buyer contact person name', max_length=200)),
                ('company', models.CharField(help_text='Company / Importer Name', max_length=255)),
                ('email', models.EmailField(help_text='Direct contact email', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone or WhatsApp number with country code', max_length=50)),
                ('category', models.CharField(blank=True, default='General Inquiry', max_length=150)),
                ('product_title', models.CharField(blank=True, default='', max_length=255)),
                ('volume', models.CharField(blank=True, default='1x 20ft Container (FCL)', max_length=150)),
                ('port', models.CharField(blank=True, default='', help_text='Destination Seaport / Airport / Country', max_length=200)),
                ('notes', models.TextField(blank=True, default='', help_text='Custom requirements, specifications, target pricing, GSM, etc.')),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Quoted', 'Quoted'), ('In Production', 'In Production'), ('Closed', 'Closed')], default='New', max_length=50)),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Private administrative response notes')),
                ('email_sent_to_company', models.BooleanField(default=False)),
                ('email_sent_to_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commercial Inquiry / RFQ',
                'verbose_name_plural': 'Commercial Inquiries & RFQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
