# Generated by Django 5.1.15 on 2026-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A&H IMPEX', max_length=200)),
                ('legal_name', models.CharField(default='A&H Impex Global Textile Exporters (Pvt.) Ltd.', max_length=255)),
                ('tagline', models.CharField(default='Pakistan’s Premier Textile Manufacturer & Global Exporter', max_length=300)),
                ('eyebrow', models.CharField(default='Institutional Bedding • Hospitality Linens • Workwear Textiles', max_length=300)),
                ('hero_description', models.TextField(default='Vertically integrated spinning, weaving, eco-dyeing, and precision automated stitching mill delivering container-grade textile shipments to North America, Europe, Oceania, and the GCC.')),
                ('contact', models.JSONField(blank=True, default=dict, help_text='JSON containing email, phone, whatsapp, address, workingHours, emergencyNotice')),
                ('socials', models.JSONField(blank=True, default=dict, help_text='JSON containing whatsapp, linkedin, instagram, facebook, youtube links')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='JSON containing experienceYears, exportCountries, monthlyCapacity, complianceRate, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company CMS Content',
                'verbose_name_plural': 'Company CMS Content',
            },
        ),
    ]
